language: java
sudo: required
jdk:
- openjdk8
services:
- docker
#before_install:
#- docker pull tutum/mongodb
#- docker run -d -p 27017:27017 -p 28017:28017 -e AUTH=no tutum/mongodb
cache:
  directories:
  - "$HOME/.cache"
install:
- true
addons:
  apt:
    update: true
script:
- "./mvnw clean install"
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: jyy1OGHWRB6GJZhwip0s0CFR9wvWBid2O1aIsaACJjzQQczDUAYTepdJ2DeVAXr5o5vcGWckkc105RdHxau2JC1eSfhpgKcAoJA0KuBI4nVVOasTtUt95jun3iAtb3Y7/G/CH5NZOHXb/nRptI9+WPjuFLVodY+G+8JtxLqunQ9tY3KVwgOZSMWoBpjvTFxZjKPHhGwi8I6VqN2ApxZgbq5TpAUXycQKkKIjsS/Q6xlMBuqsayxB73NsNUxRZqEqcwkoDmB1quwu4ypYnQ0UhKnxx3OHLTa+dGcaas+WSFYhwPa+31rT4H3fO6V/OJ76sqHXAcVLKHwGd9VTxQrmgqjG4HmEw7Uh6IRkGhRjshjKxHSQR6nYiT7xWhbOoKuLllKwlpcmzJKkH60hbVEHjMQs28mbW1m5SLWpV6GCTJY2X8DxMuK7TMs3Hqh+COby2Oyqww8MZM9Htf7rhBcsjesONIRL/ZExKnWPSTsDlkNcKhyGoO/JrE5VK3rMuiJU1exJ3VIyUladA1aOOwwEoXg2wLvKGMImRiQxkdZoSGbZG2n7GrjqnjZSWNR/nzJ0i/cfbzMsg9/8VwABF07fA6JN9XPya1mldVsmrchRF+CXE/daJ5S6OKtUILuY+juhEX9ewJHA1Pc8cDfMQk0IvSV67oNpBp3DuDp0WPNK91U=
  app: ./target/stdbank