
language: java

sudo: required

jdk:
  - openjdk8

services:
  - docker

cache:
  directories:
  - "$HOME/.cache"

install: true

script:
  - ./mvnw clean install

after_success:
  - bash <(curl -s https://codecov.io/bash)
