language: java
sudo: required
jdk:
- openjdk8
services:
- docker
cache:
  directories:
  - "$HOME/.cache"
install:
- true
addons:
  apt:
    update: true
jobs:
  include:
    - stage: unit tests & coverage
      script:
      - "./mvnw clean install"
      after_success:
      - bash <(curl -s https://codecov.io/bash)
    - stage: deploy to dev
      deploy:
        provider: heroku
        skip_cleanup: true
        api_key:
          secure: 08280c00-52b9-4619-ba31-096fe85137ba
        app: stdbank
        script:  'curl http://stdbank.herokuapp.com/vending/loadstock'
    - stage: deploy to production
      deploy:
        provider: heroku
        skip_cleanup: true
        api_key:
          secure: 08280c00-52b9-4619-ba31-096fe85137ba
        app: stdbank-production
        script: 'curl http://stdbank.herokuapp.com/vending/loadstock'
    - stage: GitHub Release
      script: echo "deploy to github release"
      deploy:
        provider: releases
        api_key: $OAUTH_TOKEN
        skip_cleanup: true
        on:
          branch: master