CREATE TABLE SBG.PRODUCTS (
  PRODUCT_KEY BIGINT       NOT NULL,
  DESCRIPTION VARCHAR(100) NOT NULL,
  ITEM_PRICE  DOUBLE       NOT NULL,
  QUANTITY    INT          NOT NULL,
  PRIMARY KEY (PRODUCT_KEY)
);

CREATE TABLE SBG.VENDING_SALES (
  ORDER_ID        BIGINT    NOT NULL,
  DATE_OF_SALE    TIMESTAMP NOT NULL,
  NUMBER_OF_ITEMS INT       NOT NULL,
  TOTAL_VALUE     DOUBLE    NOT NULL,
  PRIMARY KEY (ORDER_ID)
);

create sequence SBG_SALES_SEQ start with 100;




