
language: java

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8

install: true

cache:
 directories:
  - $HOME/.m2

script:
  - bash <(curl -s https://codecov.io/bash)
  - ./mnvw clean install

install: true